config/routes.rb
Folio::Application.routes.draw do
  resources :resolutions

  devise_for :users
  root "resolutions#index"
  get  "about" => "pages#about"

  

end

app/models/resolution.rb
class Resolution < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :resolutions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :set_resolution, only: [:show, :edit, :update, :destroy]

  # GET /resolutions
  # GET /resolutions.json
  def index
    @resolutions = Resolution.all
  end

  # GET /resolutions/1
  # GET /resolutions/1.json
  def show
  end

  # GET /resolutions/new
  def new
    @resolution = Resolution.new
  end

  # GET /resolutions/1/edit
  def edit
  end

  # POST /resolutions
  # POST /resolutions.json
  def create
    @resolution = Resolution.new(resolution_params)

    respond_to do |format|
      if @resolution.save
        format.html { redirect_to @resolution, notice: 'Resolution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resolution }
      else
        format.html { render action: 'new' }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resolutions/1
  # PATCH/PUT /resolutions/1.json
  def update
    respond_to do |format|
      if @resolution.update(resolution_params)
        format.html { redirect_to @resolution, notice: 'Resolution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resolutions/1
  # DELETE /resolutions/1.json
  def destroy
    @resolution.destroy
    respond_to do |format|
      format.html { redirect_to resolutions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resolution
      @resolution = Resolution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resolution_params
      params.require(:resolution).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">NYRes</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Folio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  
<div class="container">
  <%= render 'layouts/header' %>
  
  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>My New Year Resolution!</h1>

<% if user_signed_in? %>
   SOMETHING
<% else %>
    <p>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %> for the webapp.
    </p>
<% end %>

app/views/resolutions/_form.html.erb
<%= form_for(@resolution) do |f| %>
  <% if @resolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resolution.errors.count, "error") %> prohibited this resolution from being saved:</h2>

      <ul>
      <% @resolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resolutions/edit.html.erb
<h1>Editing resolution</h1>

<%= render 'form' %>

<%= link_to 'Show', @resolution %> |
<%= link_to 'Back', resolutions_path %>

app/views/resolutions/index.html.erb
<h1>Listing resolutions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resolutions.each do |resolution| %>
      <tr>
        <td><%= resolution.title %></td>
        <td><%= resolution.description %></td>
        <td><%= link_to 'Show', resolution %></td>
        <td><%= link_to 'Edit', edit_resolution_path(resolution) %></td>
        <td><%= link_to 'Destroy', resolution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resolution', new_resolution_path %>

app/views/resolutions/new.html.erb
<h1>New resolution</h1>

<%= render 'form' %>

<%= link_to 'Back', resolutions_path %>

app/views/resolutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resolution.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resolution.description %>
</p>

<%= link_to 'Edit', edit_resolution_path(@resolution) %> |
<%= link_to 'Back', resolutions_path %>